# Generated by Django 2.2.1 on 2019-06-12 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_userportfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportfolio',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
